name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push cat-service
        uses: docker/build-push-action@v2
        with:
          context: ./cat-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cat-service:latest

      - name: Build and push dog-service
        uses: docker/build-push-action@v2
        with:
          context: ./dog-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dog-service:latest

      - name: Build and push animal-fact-service
        uses: docker/build-push-action@v2
        with:
          context: ./animal-fact-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/animal-fact-service:latest
